package visao;

import controle.BotaoControle;
import controle.GeniusControle;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.Timer;

import modelo.CorModelo;

public class GeniusVisao extends javax.swing.JFrame {

    GeniusControle genius;
    ArrayList<CorModelo> listaCor;
    BotaoControle botao;
    private int tempo;
    private Timer tempo5Segundos;
    private boolean flag;

    public GeniusVisao() {
        genius = new GeniusControle();
        tempo = 1000;
        flag = false;
        listaCor = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonVermelho = new javax.swing.JButton();
        jButtonVerde = new javax.swing.JButton();
        jButtonAmarelo = new javax.swing.JButton();
        jButtonAzul = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GENIUS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GENIUS");
        setFocusable(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jButtonVermelho.setBackground(new java.awt.Color(125, 0, 0));
        jButtonVermelho.setEnabled(false);
        jButtonVermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVermelhoActionPerformed(evt);
            }
        });

        jButtonVerde.setBackground(new java.awt.Color(0, 125, 0));
        jButtonVerde.setEnabled(false);
        jButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerdeActionPerformed(evt);
            }
        });

        jButtonAmarelo.setBackground(new java.awt.Color(150, 150, 0));
        jButtonAmarelo.setEnabled(false);
        jButtonAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmareloActionPerformed(evt);
            }
        });

        jButtonAzul.setBackground(new java.awt.Color(0, 0, 125));
        jButtonAzul.setEnabled(false);
        jButtonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAzulActionPerformed(evt);
            }
        });

        jButtonIniciar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(0, 102, 102));
        jButtonIniciar.setText("INICIAR");
        jButtonIniciar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jButtonIniciar.setBorderPainted(false);
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jButtonVermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jButtonAmarelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButtonAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAmarelo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButtonVermelho, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exibirSequencia() {
        tempo = 1000;
        for (int i = 0; i < genius.getRodada(); i++) {
            switch (listaCor.get(i)) {
                case VERDE:
                    botao = new BotaoControle(jButtonVerde, CorModelo.VERDE, tempo);
                    break;
                case VERMELHO:
                    botao = new BotaoControle(jButtonVermelho, CorModelo.VERMELHO, tempo);
                    break;
                case AZUL:
                    botao = new BotaoControle(jButtonAzul, CorModelo.AZUL, tempo);
                    break;
                case AMARELO:
                    botao = new BotaoControle(jButtonAmarelo, CorModelo.AMARELO, tempo);
                    break;
            }
            botao.piscarBotao();
            tempo += 2000;
        }
        habilitarBotoes();
        if (genius.getRodada() > 1 || flag) {
            tempo5Segundos.stop();
        }
        flag = true;
        CincoSegundos(tempo);
    }

    private void habilitarBotoes() {
        Timer tempo2 = new Timer(0, (ActionEvent e2) -> {
            jButtonAmarelo.setEnabled(false);
            jButtonAzul.setEnabled(false);
            jButtonVerde.setEnabled(false);
            jButtonVermelho.setEnabled(false);
            jButtonIniciar.setEnabled(false);
            jButtonIniciar.setText("EXIBINDO...");
            Timer tempo3 = new Timer(tempo, (ActionEvent e) -> {
                jButtonAmarelo.setEnabled(true);
                jButtonAzul.setEnabled(true);
                jButtonVerde.setEnabled(true);
                jButtonVermelho.setEnabled(true);
                jButtonIniciar.setEnabled(true);
                jButtonIniciar.setText("REINICIAR");
            });
            tempo3.setRepeats(false);
            tempo3.start();

        });
        tempo2.setRepeats(false);
        tempo2.start();
    }

    private void desabilitarBotoes() {
        jButtonAmarelo.setEnabled(false);
        jButtonAzul.setEnabled(false);
        jButtonVerde.setEnabled(false);
        jButtonVermelho.setEnabled(false);
        jButtonIniciar.setText("INICIAR");
    }

    private void CincoSegundos(int tempo) {
        tempo5Segundos = new Timer(tempo + 5000, (ActionEvent e) -> {
            genius.msgTempoExpeirado();
            genius.recomecarRodada();
            desabilitarBotoes();
        });
        tempo5Segundos.setRepeats(false);
        tempo5Segundos.start();
    }

    private void verificarRodada() {
        if (genius.getIndex() == genius.getRodada() - 1) {
            if (genius.getIndex() == 7 || 8 == genius.getRodada()) {
                genius.msgParabens();
                tempo5Segundos.stop();
                genius.recomecarRodada();
                desabilitarBotoes();
            } else {
                genius.zerarIndex();
                genius.setRodada();
                exibirSequencia();
            }
        } else {
            genius.setIndex();
        }
    }


    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        listaCor.clear();
        listaCor = genius.gerarListaCor();
        genius.recomecarRodada();
        genius.zerarIndex();
        if (genius.getRodada() > 1 || flag) {
            tempo5Segundos.stop();
        }
        exibirSequencia();
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzulActionPerformed
        tempo5Segundos.stop();
        CincoSegundos(2000);
        tempo5Segundos.start();
        if (genius.verificarCor(CorModelo.AZUL)) {
            verificarRodada();
        } else {
            tempo5Segundos.stop();
            genius.msgPressionarBotaoErrado();
            genius.recomecarRodada();
            desabilitarBotoes();
        }
    }//GEN-LAST:event_jButtonAzulActionPerformed

    private void jButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerdeActionPerformed
        tempo5Segundos.stop();
        CincoSegundos(2000);
        tempo5Segundos.start();
        if (genius.verificarCor(CorModelo.VERDE)) {
            verificarRodada();
        } else {
            tempo5Segundos.stop();
            genius.msgPressionarBotaoErrado();
            genius.recomecarRodada();
            desabilitarBotoes();
        }
    }//GEN-LAST:event_jButtonVerdeActionPerformed

    private void jButtonVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVermelhoActionPerformed
        tempo5Segundos.stop();
        CincoSegundos(2000);
        tempo5Segundos.start();
        if (genius.verificarCor(CorModelo.VERMELHO)) {
            verificarRodada();
        } else {
            tempo5Segundos.stop();
            genius.msgPressionarBotaoErrado();
            genius.recomecarRodada();
            desabilitarBotoes();
        }
    }//GEN-LAST:event_jButtonVermelhoActionPerformed

    private void jButtonAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmareloActionPerformed
        tempo5Segundos.stop();
        CincoSegundos(2000);
        tempo5Segundos.start();
        if (genius.verificarCor(CorModelo.AMARELO)) {
            verificarRodada();
        } else {
            tempo5Segundos.stop();
            genius.msgPressionarBotaoErrado();
            genius.recomecarRodada();
            desabilitarBotoes();
        }
    }//GEN-LAST:event_jButtonAmareloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAmarelo;
    private javax.swing.JButton jButtonAzul;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonVerde;
    private javax.swing.JButton jButtonVermelho;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
